# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='service_history',
            field=models.ManyToManyField(blank=True, to='polls.Service'),
        ),
    ]
