# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20161207_0542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='service_history',
        ),
    ]
