# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20161207_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_id',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
