# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20161207_0555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='partsNeeded',
            new_name='parts_ordered',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='partsReplaced',
            new_name='parts_to_be_ordered',
        ),
        migrations.RemoveField(
            model_name='service',
            name='serviceDate',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='department',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='running_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='serial_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='date_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='date_out',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='repaired_replaced',
            field=models.TextField(blank=True),
        ),
    ]
