# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20161207_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='battery_percentage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='concerns',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='problem',
            field=models.TextField(blank=True),
        ),
    ]
