# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20161207_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='parts_to_be_ordered',
        ),
        migrations.AddField(
            model_name='service',
            name='accident',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='breakdown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='serviced',
            field=models.BooleanField(default=False),
        ),
    ]
