# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20161207_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_pic_one',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_pic_three',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_pic_two',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
