# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20170105_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.TextField(blank=True)),
                ('part_name', models.TextField(blank=True)),
                ('part_description', models.TextField(blank=True)),
                ('cart_used', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.Cart')),
            ],
        ),
    ]
