# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_spares'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='battery',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='tyres',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='upholstery',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
