# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20170125_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='Battery: good/ok/bad',
            new_name='battery',
        ),
    ]
